server:
  port: 8083
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: atc-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  topics:
    flight: flight-topic
    survey: survey-topic